---
- name: Automated app detection rule creation via dynatrace config api
  hosts: localhost
  gather_facts: false
  vars_files:
    - variables.yml
    - ../applications-api/create_update_app.yml

  tasks:
    - name: Get list of existing app detection rules
      uri: 
        url: "{{ dt_environment_url }}{{ app_detection_rule_api }}"
        method: GET
        headers:
          Content-Type: "application/json"
          Authorization: "Api-Token {{ dt_api_token }}"
        status_code: 200
        timeout: 30
        validate_certs: false
      register: listappdetruleresponse

    - name: set app detection rule id if exists for {{ app_name }}
      set_fact:
        dt_app_det_rule_id: "{{ item }}"
      loop: "{{ listappdetruleresponse.json | json_query(app_list_query) }}"
      vars:
        app_list_query: "values[?name=='{{ app_name }}'].id"
      when: item != ""

    - name: Update application detection rule {{ app_name }}
      uri: 
        url: "{{ dt_environment_url }}{{ app_detection_rule_api }}/{{ dt_app_det_rule_id }}"
        method: PUT
        headers:
          Content-Type: "application/json"
          Authorization: "Api-Token {{ dt_api_token }}"
        body: "{{ app_detection_rule_request | to_json}}"
        status_code: 200, 201, 204
        timeout: 30
        validate_certs: false
      register: updateappdetruleresponse
      when: dt_app_id is defined and dt_app_det_rule_id is defined

    - name: Create application detection rule {{ app_name }}
      uri: 
        url: "{{ dt_environment_url }}{{ app_detection_rule_api }}"
        method: POST
        headers:
          Content-Type: "application/json"
          Authorization: "Api-Token {{ dt_api_token }}"
        body: "{{ app_detection_rule_request | to_json}}"
        status_code: 200, 201
        timeout: 30
        validate_certs: false
      register: newappresponse
      when: dt_app_id is defined and dt_app_det_rule_id is not defined
