---
- name: Automated app detection rule creation via dynatrace config api
  hosts: localhost
  gather_facts: false
  vars_files:
    - variables.yml

  tasks:
    - name: check if application-detection-rules-api state file {{ dt_environment_id }}-{{ app_name }}-app-rule-id.yml exists
      stat:
        path: "./state/{{ dt_environment_id }}-{{ app_name }}-app-rule-id.yml"
      register: appdetruleapistatefile

    - name: load vars from applications-api state file {{ app_name }}-id.yml
      include_vars: "../applications-api/state/{{ dt_environment_id }}-{{ app_name }}-id.yml"
    
    - name: load vars from application-detection-rules-api state file {{ app_name }}-app-rule-id.yml
      include_vars: "./state/{{ dt_environment_id }}-{{ app_name }}-app-rule-id.yml"
      when: appdetruleapistatefile.stat.exists

    - name: Update application detection rule {{ app_name }}
      uri:
        url: "{{ dt_environment_url }}{{ app_detection_rule_api }}/{{ dt_app_det_rule_id }}"
        method: PUT
        headers:
          Content-Type: "application/json"
          Authorization: "Api-Token {{ dt_api_token }}"
        body: "{{ app_detection_rule_request | to_json}}"
        status_code: 200, 201, 204
        timeout: 30
        validate_certs: false
      register: updateappdetruleresponse
      when: dt_app_id is defined and dt_app_det_rule_id is defined

    - name: Create application detection rule {{ app_name }}
      uri: 
        url: "{{ dt_environment_url }}{{ app_detection_rule_api }}"
        method: POST
        headers:
          Content-Type: "application/json"
          Authorization: "Api-Token {{ dt_api_token }}"
        body: "{{ app_detection_rule_request | to_json}}"
        status_code: 200, 201
        timeout: 30
        validate_certs: false
      register: newappdetruleresponse
      when: dt_app_id is defined and dt_app_det_rule_id is not defined

    - name: set app det rule id for {{ app_name }}
      set_fact:
        dt_app_det_rule_id: "{{ newappdetruleresponse.json.id }}"
      when: newappdetruleresponse.json.id is defined

    - name: Store the app detection rule id 
      copy:
        content: "dt_app_det_rule_id: {{ dt_app_det_rule_id | quote }}"
        dest: "./state/{{ dt_environment_id }}-{{ app_name }}-app-rule-id.yml"