---
- name: Automated app and detection rules creation via dynatrace config api
  hosts: localhost
  gather_facts: false
  vars_files:
    - variables.yml

  tasks:
    - name: check if applications-api state file {{ dt_environment_id }}-{{ app_name }}-id.yml exists
      stat:
        path: "./state/{{ dt_environment_id }}-{{ app_name }}-app-id.yml"
      register: appapistatefile

    - name: load vars from applications-api state file {{ dt_environment_id }}-{{ app_name }}-id.yml
      include_vars: "../applications-api/state/{{ dt_environment_id }}-{{ app_name }}-id.yml"
      when: appapistatefile.stat.exists

    - name: Update application {{ app_name }}
      uri: 
        url: "{{ dt_environment_url }}{{ application_api }}/{{ existing_dt_app_id }}"
        method: PUT
        headers:
          Content-Type: "application/json"
          Authorization: "Api-Token {{ dt_api_token }}"
        body: "{{ application_request | to_json}}"
        status_code: 200, 201, 204
        timeout: 30
        validate_certs: false
      register: updateappresponse
      when: dt_app_id is defined

    - name: Create application {{ app_name }}
      uri: 
        url: "{{ dt_environment_url }}{{ application_api }}"
        method: POST
        headers:
          Content-Type: "application/json"
          Authorization: "Api-Token {{ dt_api_token }}"
        body: "{{ application_request | to_json}}"
        status_code: 200, 201
        timeout: 30
        validate_certs: false
      register: newappresponse
      when: dt_app_id is not defined

    - name: set app id if it exists for {{ app_name }}
      set_fact:
        dt_app_id: "{{ newappresponse.json.id }}"
      when: newappresponse.json.id is defined

    - name: set app id if it exists for {{ app_name }}
      set_fact:
        dt_app_id: "{{ existing_dt_app_id }}"
      when: existing_dt_app_id is defined

    - name: Store the app id to be used by the app detection rule
      copy:
        content: "dt_app_id: {{ dt_app_id | quote }}"
        dest: "./state/{{ dt_environment_id }}-{{ app_name }}-id.yml"

    - name: print app url
      debug:
        msg: "{{ dt_environment_url }}/#uemapplications/uemappmetrics;uemapplicationId={{ dt_app_id }}"

- name: Include a play after another play
  import_playbook: ../application-detection-rules-api/create_update_app_det_rule.yml